---
abstract: 'Manage a FIFO queue of tasks to perform.'
author:
  - 'cPanel, Inc. <cpan@cpanel.net>'
build_requires:
  Carp: 0
  Cwd: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cPanel-TaskQueue
requires:
  Fcntl: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Long: 0
  POSIX: 0
  Storable: 0
  Term::ReadLine: 0
  Text::Wrap: 0
  Unix::PID: 0.21
  YAML::Syck: 0
version: 0.602
