--- #YAML:1.0
name:               cPanel-TaskQueue
version:            0.4
abstract:           FIFO queue of tasks to perform
author:
    - cPanel, Inc. <cpan@cpanel.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Fcntl:           0
    File::Path:      0
    POSIX:           0
    Term::ReadLine:  0
    Test::More:      0
    YAML::Syck:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
